# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    skip_metadata_api_check     = true
    bucket                      = "exam-state"
    dynamodb_table              = "exam_lock_id"
    encrypt                     = true
    key                         = "./terraform.tfstate"
    region                      = "ap-southeast-1"
    skip_credentials_validation = true
  }
}
